services:
  monitorhandler:
    image: monitorhandler
    build:
      context: .
      dockerfile: MonitorHandler/Dockerfile

  viewtelegrambot:
    image: viewtelegrambot
    build:
      context: .
      dockerfile: ViewTelegramBot/Dockerfile
